name: build-images
on:
  workflow_dispatch: {}

  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    # Run ONLY when:
    # - the PR was merged
    # - it was your auto-PR (branch starts with chore/refresh-locks-)
    # - and it has the "refresh-locks" label added in action1
    if: >-
      ${{
        github.event.pull_request.merged == true &&
        startsWith(github.event.pull_request.head.ref, 'chore/refresh-locks-') &&
        contains(github.event.pull_request.labels.*.name, 'refresh-locks')
      }}
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NS: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        # Build exactly the merged commit
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Read version
        id: ver
        run: echo "version=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Setup Node (for frontend context)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend deps (workspace cache for Docker layer cache)
        working-directory: services/frontend
        run: npm ci || true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images
        run: |
          set -e
          VERSION="${{ steps.ver.outputs.version }}"
          docker buildx build --push -t "$REGISTRY/$IMAGE_NS/rag-backend:${VERSION}" -f services/rag-backend/Dockerfile .
          docker buildx build --push -t "$REGISTRY/$IMAGE_NS/admin-backend:${VERSION}" -f services/admin-backend/Dockerfile .
          docker buildx build --push -t "$REGISTRY/$IMAGE_NS/document-extractor:${VERSION}" -f services/document-extractor/Dockerfile .
          docker buildx build --push -t "$REGISTRY/$IMAGE_NS/mcp-server:${VERSION}" -f services/mcp-server/Dockerfile .
          docker buildx build --push -t "$REGISTRY/$IMAGE_NS/frontend:${VERSION}" -f services/frontend/apps/chat-app/Dockerfile .
          docker buildx build --push -t "$REGISTRY/$IMAGE_NS/admin-frontend:${VERSION}" -f services/frontend/apps/admin-app/Dockerfile .

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Capture image digests
        run: |
          VERSION="${{ steps.ver.outputs.version }}"
          : > image-digests.json
          for ref in \
            "$REGISTRY/$IMAGE_NS/rag-backend:${VERSION}" \
            "$REGISTRY/$IMAGE_NS/admin-backend:${VERSION}" \
            "$REGISTRY/$IMAGE_NS/document-extractor:${VERSION}" \
            "$REGISTRY/$IMAGE_NS/mcp-server:${VERSION}" \
            "$REGISTRY/$IMAGE_NS/frontend:${VERSION}" \
            "$REGISTRY/$IMAGE_NS/admin-frontend:${VERSION}"
          do
            svc=$(basename "${ref%:*}")
            digest=$(docker buildx imagetools inspect "$ref" --format '{{json .Manifest.Digest}}' | jq -r . || true)
            tmp=$(mktemp)
            jq --arg s "$svc" --arg t "$VERSION" --arg d "$digest" \
               '.[$s] = {"tag": $t, "digest": $d}' \
               image-digests.json > "$tmp" || echo '{}' > image-digests.json
            mv "$tmp" image-digests.json || true
          done

      - name: Upload digests
        uses: actions/upload-artifact@v4
        with:
          name: image-digests
          path: image-digests.json
