name: publish-chart
on:
  workflow_dispatch: {}

  workflow_run:
    workflows: [create-release]
    types: [completed]

permissions:
  contents: read
  packages: write

jobs:
  chart:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR for Helm OCI
        run: echo ${{ secrets.GHCR_PAT }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and push chart(s)
        run: |
          set -e
          for chart in infrastructure/*/Chart.yaml; do
            chart_dir=$(dirname "$chart")
            helm dependency update "$chart_dir" || true
            helm package "$chart_dir" --destination .
          done
          for tgz in *.tgz; do
            name=$(basename "$tgz" .tgz)
            helm push "$tgz" oci://ghcr.io/${{ github.repository_owner }}/charts
          done
