name: publish-chart
run-name: publish-chart (post-build-images)
on:
  workflow_dispatch:
  workflow_run:
    workflows: [build-images]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  chart:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} or ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout release tag from triggering run
        run: |
          git fetch --tags --force
          HEAD_SHA="${{ github.event.workflow_run.head_sha }}"
          if [ -n "$HEAD_SHA" ]; then
            TAG=$(git tag --points-at "$HEAD_SHA" | head -n 1 || true)
            if [ -z "$TAG" ]; then
              TAG=$(git describe --tags --abbrev=0 "$HEAD_SHA" 2>/dev/null || true)
            fi
          else
            # Manual dispatch: fall back to latest tag
            TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
          fi
          if [ -z "$TAG" ]; then
            echo "No tag found (head_sha=$HEAD_SHA)" >&2
            exit 1
          fi
          git checkout "$TAG"
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
          echo "APP_VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Expose app version
        id: meta
        run: echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT

      - name: Create branch for chart bump
        run: |
          git checkout -b chore/chart-bump-${APP_VERSION}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR for Helm OCI
        run: echo ${{ secrets.GHCR_PAT }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Setup Python (for bump script)
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install bump script deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pyyaml==6.0.2" "packaging==25.0"

      - name: Bump Chart.yaml (set release version)
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
        run: |
          python tools/bump_chart_versions.py --app-version "$APP_VERSION"

      - name: Package and push chart(s)
        run: |
          set -e
          CHART_DIR="infrastructure/rag"
          if [ ! -f "$CHART_DIR/Chart.yaml" ]; then
            echo "Expected chart at $CHART_DIR/Chart.yaml not found" >&2
            exit 1
          fi
          mkdir -p dist
          echo "Processing $CHART_DIR"
          helm dependency update "$CHART_DIR" || true
          helm package "$CHART_DIR" --destination dist
          for tgz in dist/*.tgz; do
            helm push "$tgz" oci://ghcr.io/${{ github.repository_owner }}/charts
          done

      - name: Create PR for chart version bumps
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: chore/chart-bump-${{ steps.meta.outputs.app_version }}
          title: "chore(release): bump chart versions to ${{ steps.meta.outputs.app_version }}"
          body: |
            Persist Chart.yaml appVersion/version to match release ${{ steps.meta.outputs.app_version }}.
          commit-message: "chore(release): bump charts to ${{ steps.meta.outputs.app_version }}"
          add-paths: |
            infrastructure/**/Chart.yaml
          labels: chart-bump
